## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

#### Import Numpy:

In [1]:
import numpy as np

#### Init:

In [2]:
# Creat two arrays:
arr = np.array([1, 6, 7, 56, 3, 5, 4, 9, 10, 21])
arr2 = np.arange(0,10)

In [3]:
# Show:
arr

array([ 1,  6,  7, 56,  3,  5,  4,  9, 10, 21])

In [4]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Main:

In [5]:
# Căn mỗi phần tử trong mảng:
np.sqrt(arr)

array([1.        , 2.44948974, 2.64575131, 7.48331477, 1.73205081,
       2.23606798, 2.        , 3.        , 3.16227766, 4.58257569])

In [11]:
# Tính e^x (Với x là các phần tử trong mảng)
np.exp(arr2)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [13]:
# Tính sin(x) - (Với x là các phần tử trong mảng):
np.sin(arr)

array([ 0.84147098, -0.2794155 ,  0.6569866 , -0.521551  ,  0.14112001,
       -0.95892427, -0.7568025 ,  0.41211849, -0.54402111,  0.83665564])

In [14]:
# Tính log(x) - (Với x là các phần tử trong mảng):
np.log(arr)

array([0.        , 1.79175947, 1.94591015, 4.02535169, 1.09861229,
       1.60943791, 1.38629436, 2.19722458, 2.30258509, 3.04452244])