### Set up 2D array

Cài đặt giá trị cho hàng/ cột/ vùng trong ma trận

#### Import Numpy:

In [1]:
import numpy as np

#### Init:

In [2]:
# Tao ma trận 0 kích thước 10 x 8:
arr2d = np.zeros((10, 8), dtype = int)

# Show:
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

#### Set up row:

In [3]:
# Cài đặt giá trị hàng 3 là 100:
arr2d[2] = 100

# Show:
arr2d

array([[  0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0],
       [100, 100, 100, 100, 100, 100, 100, 100],
       [  0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0]])

#### Set up column:

In [4]:
# Cài đặt giá trị cột 6 là 200:
arr2d[:, 5] = 200

# Show:
arr2d

array([[  0,   0,   0,   0,   0, 200,   0,   0],
       [  0,   0,   0,   0,   0, 200,   0,   0],
       [100, 100, 100, 100, 100, 200, 100, 100],
       [  0,   0,   0,   0,   0, 200,   0,   0],
       [  0,   0,   0,   0,   0, 200,   0,   0],
       [  0,   0,   0,   0,   0, 200,   0,   0],
       [  0,   0,   0,   0,   0, 200,   0,   0],
       [  0,   0,   0,   0,   0, 200,   0,   0],
       [  0,   0,   0,   0,   0, 200,   0,   0],
       [  0,   0,   0,   0,   0, 200,   0,   0]])

#### Set up area:

In [5]:
arr2d[5:9, 1:4] = 999

# Show:
arr2d

array([[  0,   0,   0,   0,   0, 200,   0,   0],
       [  0,   0,   0,   0,   0, 200,   0,   0],
       [100, 100, 100, 100, 100, 200, 100, 100],
       [  0,   0,   0,   0,   0, 200,   0,   0],
       [  0,   0,   0,   0,   0, 200,   0,   0],
       [  0, 999, 999, 999,   0, 200,   0,   0],
       [  0, 999, 999, 999,   0, 200,   0,   0],
       [  0, 999, 999, 999,   0, 200,   0,   0],
       [  0, 999, 999, 999,   0, 200,   0,   0],
       [  0,   0,   0,   0,   0, 200,   0,   0]])