### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

#### Import Numpy:

In [1]:
import numpy as np

#### Init:

In [2]:
# Tao ma trận 0 kích thước 10 x 8:
arr2d = np.zeros((10, 8), dtype = int)

# Show:
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [3]:
# Lấy số hàng của ma trận:
rows = arr2d.shape[0]

# Show:
rows

10

In [4]:
# Cài đặt ma trận:
for i in range(rows):
    arr2d[i] = i

# Show:
arr2d

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9]])

#### Fancy indexing:

In [5]:
arr2d[[1, 2, 8]]

array([[1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2],
       [8, 8, 8, 8, 8, 8, 8, 8]])

In [6]:
arr2d[[8, 5, 6, 9, 3]]

array([[8, 8, 8, 8, 8, 8, 8, 8],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6],
       [9, 9, 9, 9, 9, 9, 9, 9],
       [3, 3, 3, 3, 3, 3, 3, 3]])