## Arithmetic

You can easily perform array with array arithmetic, or scalar with array arithmetic. Let's see some examples:

#### Import Numpy:

In [1]:
import numpy as np

#### Init:

In [2]:
# Creat two arrays:
arr = np.array([1, 6, 7, 56, 3, 5, 4, 9, 10, 21])
arr2 = np.arange(0,10)

In [3]:
# Show:
arr

array([ 1,  6,  7, 56,  3,  5,  4,  9, 10, 21])

In [4]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Main:

In [5]:
arr + arr2 

array([ 1,  7,  9, 59,  7, 10, 10, 16, 18, 30])

In [6]:
arr - arr2

array([ 1,  5,  5, 53, -1,  0, -2,  2,  2, 12])

In [7]:
arr * arr2

array([  0,   6,  14, 168,  12,  25,  24,  63,  80, 189])

In [8]:
# Warning on division by zero, but not an error!
# Just replaced with "nan"
arr2 / arr2

C:\Users\Dell\anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [9]:
# Also warning, but not an error instead infinity
arr / arr2

C:\Users\Dell\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in true_divide
  


array([        inf,  6.        ,  3.5       , 18.66666667,  0.75      ,
        1.        ,  0.66666667,  1.28571429,  1.25      ,  2.33333333])

In [10]:
1 / arr2

C:\Users\Dell\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [11]:
arr2 / arr

array([0.        , 0.16666667, 0.28571429, 0.05357143, 1.33333333,
       1.        , 1.5       , 0.77777778, 0.8       , 0.42857143])

In [12]:
arr ** 2

array([   1,   36,   49, 3136,    9,   25,   16,   81,  100,  441],
      dtype=int32)