## 2D array slicing:
The format is **arr_2d[row][col]** or **arr_2d[row,col]**

#### Import Numpy:

In [1]:
import numpy as np

#### Init:

In [2]:
arr_2d = np.array(([1, 2, 3, 17], [4, 5, 6, 18], [8, 9, 10, 19], [11, 12, 13, 20], [14, 15, 16, 21]))

# Show:
arr_2d

array([[ 1,  2,  3, 17],
       [ 4,  5,  6, 18],
       [ 8,  9, 10, 19],
       [11, 12, 13, 20],
       [14, 15, 16, 21]])

#### Array slicing:

### Row:

In [3]:
# Cắt lấy 2 hàng đầu:
arr_2d[:2]

array([[ 1,  2,  3, 17],
       [ 4,  5,  6, 18]])

In [4]:
# Cắt lấy 2 hàng cuối:
arr_2d[3:]

array([[11, 12, 13, 20],
       [14, 15, 16, 21]])

In [5]:
# Cắt lấy hàng 3 và hàng 4:
arr_2d[2:4]

array([[ 8,  9, 10, 19],
       [11, 12, 13, 20]])

In [6]:
# Lấy giá trị hàng 3:
arr_2d[2]

array([ 8,  9, 10, 19])

### Column:

In [7]:
# Cắt lấy 3 cột đầu:
arr_2d[:, :3]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

In [8]:
# Cắt lấy 2 cột cuối:
arr_2d[:, 2:]

array([[ 3, 17],
       [ 6, 18],
       [10, 19],
       [13, 20],
       [16, 21]])

In [9]:
# Lấy giá trị cột thứ 3:
arr_2d[:, 3]

array([17, 18, 19, 20, 21])

In [10]:
# Cắt lấy cột 3:
arr_2d[:, 2:3]

array([[ 3],
       [ 6],
       [10],
       [13],
       [16]])

### Mix:

In [11]:
arr_2d[2:, :3]

array([[ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])

In [12]:
arr_2d[1:3, 1:3]

array([[ 5,  6],
       [ 9, 10]])

In [13]:
arr = arr_2d[2:, :3]

In [14]:
arr

array([[ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16]])