#### Import Numpy:

In [1]:
import numpy as np

#### Init:

In [2]:
# Matrix:
mat = np.arange(1,26).reshape(5,5)

# Show Matrix:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### Tổng lần lượt các cột:

In [3]:
mat.sum(axis = 0)

array([55, 60, 65, 70, 75])

#### Tổng lần lượt các hàng:

In [4]:
mat.sum(axis = 1)

array([ 15,  40,  65,  90, 115])