#### Import Numpy:

In [1]:
import numpy as np

#### Mảng một chiều 10 số 0:

In [2]:
np.zeros(10, int) # Không có int thì sẽ để mặc định là float, khi đó sẽ có dạng 0.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### Mảng 2 chiều 5 x 4 gồm các số 0 :

In [3]:
np.zeros((5, 4), int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

#### Tương tự với mảng gồm các số 1:

In [4]:
# Mảng 1 chiều:
np.ones(10, int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [5]:
# Mảng 2 chiều:
np.ones((3, 2), int)

array([[1, 1],
       [1, 1],
       [1, 1]])

#### Các mảng số nguyên khác:

In [6]:
np.ones(8, int) * 12

array([12, 12, 12, 12, 12, 12, 12, 12])

In [7]:
np.zeros(9, int) + 65

array([65, 65, 65, 65, 65, 65, 65, 65, 65])

#### Các mảng số thập phân:

In [8]:
np.ones(8) * 2.67594

array([2.67594, 2.67594, 2.67594, 2.67594, 2.67594, 2.67594, 2.67594,
       2.67594])

In [9]:
np.zeros(9) + 0.6451315

array([0.6451315, 0.6451315, 0.6451315, 0.6451315, 0.6451315, 0.6451315,
       0.6451315, 0.6451315, 0.6451315])