## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

#### Import Numpy:

In [1]:
import numpy as np

#### Init:

In [2]:
# Tạo mảng:
arr = np.array([1, 6, 7, 1, 3, 5, 4, 9, 7, 10])

# Show:
arr

array([ 1,  6,  7,  1,  3,  5,  4,  9,  7, 10])

#### Selection:


In [3]:
arr > 5

array([False,  True,  True, False, False, False, False,  True,  True,
        True])

In [4]:
bool_arr =  arr > 5

# Show:
bool_arr

array([False,  True,  True, False, False, False, False,  True,  True,
        True])

In [5]:
# Những số > 5 trong mảng:
arr[bool_arr]

array([ 6,  7,  9,  7, 10])

In [6]:
# Hoặc:
arr[arr > 5]

array([ 6,  7,  9,  7, 10])

In [7]:
# Hoặc:
x = 5
arr[arr > x]

array([ 6,  7,  9,  7, 10])